//Rest API Ag360Api
//Version 1.0 (Alain Dubé)
//Plug-IN : vscode-restclient (Huachao)
//   https://github.com/Huachao/vscode-restclient
@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json
//Aller chercher l'application TOKEN valide en utilisant l'action POST getAppToken
//:3001/users/login

@applicationTOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmFtZSI6IjIzNDAyMzBAY2VnZXByZGwuY2EiLCJpYXQiOjE3MjkyODAzOTJ9.GJRV82S_tR-dTLaxEcWSZPZ6Sl7jTU6rWH5vtwXLyec
@BearerTOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsYWluLmR1YmVAY2VnZXByZGwuY2EiLCJpYXQiOjE3MjkyNzc0MzMsImV4cCI6MTcyOTI4NDYzM30.sg708_jeoEA_L_Lkb7lNhSRbuHdAf8OnPeN3CsKzNOQ
@BearerRefreshTOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsImVtYWlsIjoiYWxhaW4uZHViZUBjZWdlcHJkbC5jYSIsImlhdCI6MTcwNzkzNzkwMywiZXhwIjoxNzA4NTQyNzAzfQ.M6aqOKrHBkZRyA0MOZtp1XnrxWOQTtwk7A9gDNiu8t0

###
GET http://localhost:3001/


###
GET http://{{host}}/

###
GET http://{{host}}/users/getAppToken
Content-Type:{{contentType}}

{
    "email": "2340230@cegeprdl.ca",
    "pass": "220G3[YvNVuUxBhuXyFc.Yrn^hT&K#zyBwE;bntV"
  }

###
POST http://{{host}}/users/register
Content-Type:{{contentType}}

{
    "appKey": "{{applicationTOKEN}}",
    "nom": "Jean",
    "prenom": "Paul",
    "email": "2312345@cegeprdl.ca",
    "password": "LaVie123"
  }

###
POST http://{{host}}/users/login
Content-Type:{{contentType}}

{
    "appKey": "{{applicationTOKEN}}",
    "email": "alain.dube@cegeprdl.ca",
    "password": "EcoleDuWeb@Secure"
  }

###
GET http://{{host}}/questionnaire-mon-choix-programme/getAllQuestions
Authorization: Bearer {{BearerTOKEN}}
Content-Type:{{contentType}}

{

  }



###
GET http://{{host}}/questionnaire-moyens-pour-reussir/getReponseRessourceActionFromUser
Authorization: Bearer {{BearerTOKEN}}
Content-Type:{{contentType}}

{

  }

###
GET http://{{host}}/api/welcome
Authorization: Bearer {{BearerTOKEN}}
Content-Type:{{contentType}}


###
DELETE http://{{host}}/api/auth/resetAll
Content-Type:{{contentType}}

{
    "appKey": "{{applicationTOKEN}}",
    "email":"admin@cegeprdl.ca",
    "pass":"password1263"
  }
  
###
POST http://{{host}}/api/auth/getAppToken
Content-Type:{{contentType}}

{
    "email":"admin@cegeprdl.ca",
    "pass":"password1263"
}



###
POST http://{{host}}/api/auth/register
Content-Type:{{contentType}}
Authorization: Bearer {{BearerTOKEN}}

{
     "appKey": "{{applicationTOKEN}}",
     "firstName": "Alain",
      "lastName": "Dube",
      "email": "alain.dube@cegeprdl.ca",
      "passWord": "Patate123",
      "active": "1",
      "road": "Fraser",
      "state": "Québec",
      "country": "Canada",
      "zip": "G5R6A1",
      "city": "Rivière-du-Loup",
      "listCity":[],
      "securityQuestion": "Le meilleur enseignants de l'école du Web",
      "securityAnswer": "C'est moi",
      "description": "Enseignant de l'Ecole du WEB"
  }


###
POST http://{{host}}/api/auth/login
Content-Type:{{contentType}}

{
"appKey": "{{applicationTOKEN}}",
"pass":"Patate123",
"email":"alain.dube@cegeprdl.ca"
}


###
POST http://{{host}}/api/auth/login
Content-Type:{{contentType}}

{
  "appKey": "{{applicationTOKEN}}",
  "pass":"password1263",
  "email":"admin@admin.ca"
}


###
GET http://{{host}}/api/auth/showAllUsers
Content-Type:{{contentType}}
Authorization: Bearer {{BearerTOKEN}}

###
PUT http://{{host}}/api/auth/type
Content-Type:{{contentType}}
Authorization: Bearer {{BearerTOKEN}}

{
  "appKey": "{{applicationTOKEN}}",
  "email":"alain.dube@cegeprdl.ca"
}